In [1]:
import numpy as np

In [4]:
# Task 1

# adding data in array using arrange 
HR_dep=np.arange(1,4)  
IT_dep=np.arange(4,19)
Finance_dep=np.arange(19,24)
Sales_dep=np.arange(24,31)

# Displaying data from all array 
print(HR_dep)
print(IT_dep)
print(Finance_dep)
print(Sales_dep)

[1 2 3]
[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[19 20 21 22 23]
[24 25 26 27 28 29 30]


In [12]:
# Task 2
# using array to add data  
HR_dep_sal=np.array([50,60,57])
it=[67]
IT_dep_sal=np.array(it*15) # repeating same value 15 times
Finance_dep_sal=np.array([60,65,50,70,87])
Sales_dep_sal=np.array([50,60,65,90,56,65,71])

#print values
print(HR_dep_sal)
print(IT_dep_sal)
print(Finance_dep_sal)
print(Sales_dep_sal)

[50 60 57]
[67 67 67 67 67 67 67 67 67 67 67 67 67 67 67]
[60 65 50 70 87]
[50 60 65 90 56 65 71]


In [15]:
# Task 3
# average salary for each dep 
a=HR_dep_sal.mean()
b=IT_dep_sal.mean()
c=Finance_dep_sal.mean()
d=Sales_dep_sal.mean()

#printing average salary for all department
print("average salary in HR_dep ",a)
print("average salary in IT_dep ",b)
print("average salary in Finance_dep ",c)
print("average salary in Sales_dep ",d)

# highest average salary
e=max(a,b,c,d)
print("-----------------------------------------")
# giving condition to find dep name
if e==a:print("HR_dep have highest average salary ")
elif e==b:print("IT_dep have highest average salary ")
elif e==c:print("Finance_dep have highest average salary ")
else: print("Sales_dep have highest average salary ")

average salary in HR_dep  55.666666666666664
average salary in IT_dep  67.0
average salary in Finance_dep  66.4
average salary in Sales_dep  65.28571428571429
-----------------------------------------
IT_dep have highest average salary 


In [16]:
# Task 4
# using max function to find highest salaries in HR and Finance
print("Highest salary in HR_dep is ",max(HR_dep_sal))
print("Highest salary in Finance_dep is ",max(Finance_dep_sal))


Highest salary in HR_dep is  60
Highest salary in Finance_dep is  87


In [18]:
# task 5

# updating salaries of it department and giving them 5% bonus
for i in range(0,len(IT_dep_sal)):
    IT_dep_sal[i]=IT_dep_sal[i]+(IT_dep_sal[i]*0.05)
print(IT_dep_sal)

[70 70 70 70 70 70 70 70 70 70 70 70 70 70 70]
